#config/doctrine/Model.BadgeAssertion.dcm.yml
Model\BadgeAssertion:
    type: entity
    table: badge_assertion
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        badge_id:
            type: integer
        recipient_id:
            type: integer
        issued_on:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    oneToOne:
        badge: 
            targetEntity: Model\Badge
            joinColumn:
                name: badge_id
                referencedColumnName: id
        recipient:
            targetEntity: Model\Recipient
            joinColumn:
                name: recipient_id
                referencedColumnName: id