#config/doctrine/Model.Recipient.dcm.yml
Model\Recipient:
    type: entity
    table: recipient
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
    oneToMany:
        badge_assertion:
            targetEntity: Model\BadgeAssertion
            mappedBy: badge_assertion