#config/doctrine/Model.BadgeAssertion.dcm.yml
Model\BadgeAssertion:
    type: entity
    table: badge_assertion
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        issued_on:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        badge: 
            targetEntity: Model\Badge
            inversedBy: badge_assertion
            joinColumn:
                name: badge_id
                referencedColumnName: id
        recipient:
            targetEntity: Model\Recipient
            inversedBy: badge_assertion
            joinColumn:
                name: recipient_id
                referencedColumnName: id
        issued_by:
            targetEntity: Model\User
            joinColumn:
                name: issued_by
                referencedColumnName: id