#config/doctrine/Model.Badge.dcm.yml
Model\Badge:
    type: entity
    table: badge
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        desc:
            column: `desc`
            type: text
        image_url:
            type: string
            length: 255
            nullable: true
        criteria:
            type: text
        created:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    oneToMany:
        badge_assertion:
            targetEntity: Model\BadgeAssertion
            mappedBy: badge
    manyToOne:
        created_by:
            targetEntity: Model\User
            joinColumn:
                name: created_by
                referencedColumnName: id